### ISSUE TITLE
User feedback and experience

### ISSUE THREAD

**Issue by c0pperdragon** [c0pperdragon/A-VideoBoard#5]
Please let the community know how this device works for you, what the pitfalls were and maybe upload some pictures as well.

**Comment by olliraa** [comment]
Just finished installing the A-videoboad into my ZX48k. My Speccy is an Issue 2 one with the following modifications/repairs:

-All caps replaced.
-A-videoboard installed and RF tank removed
-The infamous 7805 regulator replaced with a DC-DC step down converter pcb -> way less heat and more juice :)
-128k RAM with added GAL logic board -> this is 100% 128K Speccy compliant unlike the more simple "just add ram chips" mods. All RAM chips are also socketed now.
-vLA82 ULA replacement (original was somewhat broken)

The picture quality with the A-videoboard is simply amazing. My Speccy is connected to Sony BVM20F1E -> happy times :)

I just got the computer case closed (pun intended), which with the mod is kinda challenging, but doable. I'll add some pictures afterwards. 

Just a few tips, how I solved some challenges. The original designer of the board kindly gave me some really good advice during my modding experience:

-Tap the D0-D7 signals directly from the RAM chips (pin 14) respectively. D7 is the left most chip.
-I tapped the WR, IQREQ and CAS signals directly from the ULA *under* the pcb = socket solder points. There's enough room for the wires to go around the pcb back and actually the wire length is exactly the same as when tapping these signals from top of the pcb. Not the prettiest solution, but secure and solid :)
