### ISSUE TITLE
Test pattern

### ISSUE THREAD

**Issue by Zer02dk** [c0pperdragon/A-VideoBoard#8]
How is the test pattern suppose to look?
Mine looks strange, any ideas what could be the issue?

![20210312_121514](https://user-images.githubusercontent.com/62931766/110933363-f0ff6080-832c-11eb-94dd-ae58372a89c5.jpg)

**Comment by c0pperdragon** [comment]
The top left should be a rectangle with the 256 lum/hue combinations of Atari machined. Then there is a bar with the 16 colors of the C64. Then some moving lines. Below are three gradients with 32 steps each. One for Y one for Pb, one for Pr.
In your image it seems that all your DAC resistor networks are completely wrong/unsoldered/shorted. Or your monitor has a digital input.

**Comment by Zer02dk** [comment]
I forgot to mention I'm using the RGBtoHDMI by hoglet67. But it could very well be my SMD soldering skills.

**Comment by c0pperdragon** [comment]
OK, this is a completely different matter then.
The RGBtoHDMI can not convert just any analog YPbRP or RGB signal to HDMI. Basically it needs to get this in a kind of digitial or quantized form very specific to the machine in question.
This test pattern generator is just for use with "normal" YPbPr displays and will not work with the RGBtoHDMI.

I you use the A-VideoBoard in one of my supported machines (C64/C128, Atari 8bit, ZX Spectrum), then it can be configured (with jumper links) to generate such a quantized output signal. I guess there is no proper documention on this feature in the projects yet. Tell me which machine you are using the board and I can give you better instructions.

**Comment by Zer02dk** [comment]
Ah, Im installing it in a C64. My bord is the one from your "C64-Video-Enhancement" project.
I havent installed it yes i wanted to test the bord first. But let me try and install it first. Just need to desolder that VICII chip.
Would you be intrested in my excess bare PCB's? I have 4 sets.

**Comment by c0pperdragon** [comment]
Thank you, but I don't intend to build any more of these sets as they are now readily available from videogameperfection.com

About the testpattern: considering that you did the upscaling with the RGBtoHDMI this looks pretty OK. I would expect these kind of quantization result.

**Comment by Zer02dk** [comment]
Finally got the C64 finished, and all seams to be working.
